### ISSUE TITLE
Update the April and May Month Offer

### ISSUE THREAD

**Issue by HNPavan** [garbhagudi/dash-ivf-next#327]
Dear Avinash,

Please update the April and May month offer on the landing page, offer details are attached below
 
[Blood Test Discounts -Essential.pdf](https://github.com/garbhagudi/dash-ivf-next/files/14814230/Blood.Test.Discounts.-Essential.pdf)

**Comment by dbugging404** [comment]
Updated on 10-04-24. 

Resolved.
