### ISSUE TITLE
Changes in landing page

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/dash-ivf-next#351]
Dear sir,

Hemanth sir has shared you Word document to make changes in the landing page. Kindly look into it and let me know the update about the changes done.

Reference link: https://www.oasisindia.in/fertility-treatment-best-ivf-clinic-karnataka-chennai/?utm_source=ET_Google&utm_medium=ET-026-A03-Non_Brand_Fertility_Infertility_Price_HI-KA&utm_campaign=ET-026-Search-Non_Brand_Fertility_HI-Conversion-KA&utm_id=21070271227&utm_term=fertility%20package&gad_source=1&gclid=Cj0KCQjwk6SwBhDPARIsAJ59Gwe4L7cb5g4UsKAI0_rt-jD_E_54GaFKn7GVrZuXZR7nlGrb8TAReVUaAvpKEALw_wcB

**Comment by garbhagudi** [comment]
I think this is not needed anymore. 

There are many new LPs that have been made since then. 

If this is still needed. Kindly reopen.
